export const abbreviations: { [key: string]: string } = {
	// Union Territories
	'Andaman and Nicobar Islands': 'ANI',
	'Port Blair': 'PB',
	Chandigarh: 'CHD',
	'Dadra and Nagar Haveli and Daman and Diu': 'DNHDD',
	Daman: 'DAM',
	Diu: 'DIU',
	Silvassa: 'SLV',
	Delhi: 'DEL',
	'New Delhi': 'NDL',
	Puducherry: 'PUD',
	Karaikal: 'KRK',
	Mahe: 'MAH',
	Yanam: 'YAN',

	// Andhra Pradesh
	'Andhra Pradesh': 'AP',
	Adoni: 'ADN',
	Amaravati: 'AMV',
	Anantapur: 'ATP',
	Chandragiri: 'CDG',
	Chittoor: 'CTR',
	Dowlaiswaram: 'DLS',
	Eluru: 'ELR',
	Guntur: 'GTR',
	Kadapa: 'KDP',
	Kakinada: 'KKD',
	Kurnool: 'KNL',
	Machilipatnam: 'MCP',
	Nagarjunakonda: 'NGK',
	Rajahmundry: 'RJM',
	Srikakulam: 'SKL',
	Tirupati: 'TPT',
	Vijayawada: 'VJW',
	Visakhapatnam: 'VSKP',
	Vizianagaram: 'VZM',
	Yemmiganur: 'YMN',

	// Arunachal Pradesh
	'Arunachal Pradesh': 'AR',
	Itanagar: 'ITN',

	// Assam
	Assam: 'AS',
	Dhuburi: 'DBR',
	Dibrugarh: 'DIB',
	Dispur: 'DIS',
	Guwahati: 'GHY',
	Jorhat: 'JRH',
	Nagaon: 'NGN',
	Sivasagar: 'SVS',
	Silchar: 'SIL',
	Tezpur: 'TZP',
	Tinsukia: 'TSK',

	// Bihar
	Bihar: 'BR',
	Ara: 'ARA',
	Barauni: 'BRU',
	Begusarai: 'BGS',
	Bettiah: 'BET',
	Bhagalpur: 'BGP',
	'Bihar Sharif': 'BHS',
	'Bodh Gaya': 'BDG',
	Buxar: 'BXR',
	Chapra: 'CPR',
	Darbhanga: 'DBG',
	Dehri: 'DHR',
	'Dinapur Nizamat': 'DNP',
	Gaya: 'GAY',
	Hajipur: 'HJP',
	Jamalpur: 'JMP',
	Katihar: 'KTR',
	Madhubani: 'MDB',
	Motihari: 'MTI',
	Munger: 'MGR',
	Muzaffarpur: 'MFP',
	Patna: 'PAT',
	Purnia: 'PRN',
	Pusa: 'PUS',
	Saharsa: 'SHS',
	Samastipur: 'SMS',
	Sasaram: 'SSR',
	Sitamarhi: 'STM',
	Siwan: 'SWN',

	// Chhattisgarh
	Chhattisgarh: 'CG',
	Ambikapur: 'ABK',
	Bhilai: 'BHL',
	Bilaspur: 'BSP',
	Dhamtari: 'DMT',
	Durg: 'DRG',
	Jagdalpur: 'JGD',
	Raipur: 'RPR',
	Rajnandgaon: 'RNG',

	// Goa
	Goa: 'GA',
	Madgaon: 'MDG',
	Panaji: 'PJI',

	// Gujarat
	Gujarat: 'GJ',
	Ahmadabad: 'AMD',
	Amreli: 'AML',
	Bharuch: 'BHR',
	Bhavnagar: 'BVG',
	Bhuj: 'BHJ',
	Dwarka: 'DWK',
	Gandhinagar: 'GND',
	Godhra: 'GDR',
	Jamnagar: 'JMN',
	Junagadh: 'JND',
	Kandla: 'KAN',
	Khambhat: 'KBT',
	Kheda: 'KHD',
	Mahesana: 'MSA',
	Morbi: 'MBI',
	Nadiad: 'NDD',
	Navsari: 'NVS',
	Okha: 'OKH',
	Palanpur: 'PLN',
	Patan: 'PTN',
	Porbandar: 'PBR',
	Rajkot: 'RKT',
	Surat: 'SRT',
	Surendranagar: 'SNR',
	Valsad: 'VLD',
	Veraval: 'VRV',

	// Haryana
	Haryana: 'HR',
	Ambala: 'AMB',
	Bhiwani: 'BHW',
	Faridabad: 'FRD',
	'Firozpur Jhirka': 'FZJ',
	Gurugram: 'GGN',
	Hansi: 'HSI',
	Hisar: 'HSR',
	Jind: 'JND',
	Kaithal: 'KTL',
	Karnal: 'KNL',
	Kurukshetra: 'KUK',
	Panipat: 'PPT',
	Pehowa: 'PHW',
	Rewari: 'RWR',
	Rohtak: 'RTK',
	Sirsa: 'SRS',
	Sonipat: 'SNP',

	// Himachal Pradesh
	'Himachal Pradesh': 'HP',
	Chamba: 'CHM',
	Dalhousie: 'DLH',
	Dharmshala: 'DHM',
	Hamirpur: 'HMP',
	Kangra: 'KNG',
	Kullu: 'KLU',
	Mandi: 'MDI',
	Nahan: 'NHN',
	Shimla: 'SHM',
	Una: 'UNA',

	// Jammu and Kashmir
	'Jammu and Kashmir': 'JK',
	Anantnag: 'ANT',
	Baramula: 'BRM',
	Doda: 'DOD',
	Gulmarg: 'GLM',
	Jammu: 'JMU',
	Kathua: 'KTH',
	Punch: 'PNC',
	Rajouri: 'RJR',
	Srinagar: 'SNR',
	Udhampur: 'UDH',

	// Continue with other states...
};
