const alarmMap = {
	accOff: 'Acc off',
	accOn: 'Acc on',
	bang: 'Crash',
	bothHandsOffSteeringWheel: 'Hand Off detection (HOD)',
	bsdBack: 'Back BSD',
	bsdFront: 'Front BSD',
	bsdLeft: 'Left BSD',
	bsdRight: 'Right BSD',
	closeProximity: 'Too close',
	drStorageFault: 'Disaster recovery storage failure',
	drift: 'Device drift',
	driverBehaviorMonitoringFailure: 'Infrared blocking',
	driverChange: 'Driver change',
	driverNotDetected: 'No Driver detected',
	external: 'Low external power',
	externalProtection: 'Low power protection',
	fatigueAlarm: 'Fatigue alarm',
	fatigueWarn: 'Fatigue warning',
	forwardCollisionWarning: 'Forward collision',
	gpsBlindZone: 'Gps Blind Zone',
	handheldPhoneCall: 'Phone Calling',
	hardBraking: 'Rollover',
	identification: 'Driver ID Detection',
	idleSpeed: 'Idle Alarm',
	inFence: 'Enter geo-fence',
	inGpsBlindSpots: 'Enter GPS blind zone',
	internal: 'Low internal power',
	ioOff: 'IO off',
	ioOn: 'IO on',
	laneShift: 'Lane shift',
	longTimeWithoutLookingAhead: 'Distracted driving',
	mainMemoryFault: 'Main Memory Fault',
	occlusion: 'Camera Blocked',
	offline: 'Device offline',
	outFence: 'Exit geo-fence',
	outGpsBlindSpots: 'Exit GPS blind zone',
	outage: 'Device power outage',
	overspeedWarning: 'High speed warning',
	overtime: 'Driving overtime',
	parking: 'Overtime parking',
	passengerOverload: 'Passenger Overload',
	pedestrianBang: 'Pedestrian collision',
	playPhone: 'Play phone',
	powerCut: 'Power cut off',
	rapid: 'Rapid acceleration',
	coverningCamera: 'Coverning Camera',
	seatBelt: 'Seat-Belt Detection',
	shake: 'Device vibration',
	slow: 'Rapid deceleration',
	smoking: 'Smoking',
	sos: 'SOS alarm',
	speed: 'Over speed alarm',
	tamper: 'Device tamper',
	unplanned: 'Unplanned Alarm',
	videoSignalLost: 'Video Signal Lost',
	wheel: 'Sharp turn',
} as const;

export type VideoAlarmType = keyof typeof alarmMap;

export function getAlarmName(alarmType: VideoAlarmType): string {
	return alarmMap[alarmType];
}
